package org.jiang.combo.accretion.salute.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.created_at
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.updated_at
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_del
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private String isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.host
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.address
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.school
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.username
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.created_at
     *
     * @return the value of message.created_at
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.created_at
     *
     * @param createdAt the value for message.created_at
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.updated_at
     *
     * @return the value of message.updated_at
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.updated_at
     *
     * @param updatedAt the value for message.updated_at
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_del
     *
     * @return the value of message.is_del
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_del
     *
     * @param isDel the value for message.is_del
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.host
     *
     * @return the value of message.host
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.host
     *
     * @param host the value for message.host
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.address
     *
     * @return the value of message.address
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.address
     *
     * @param address the value for message.address
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.school
     *
     * @return the value of message.school
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.school
     *
     * @param school the value for message.school
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setSchool(String school) {
        this.school = school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.username
     *
     * @return the value of message.username
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.username
     *
     * @param username the value for message.username
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Sun Jan 09 11:32:47 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }
}