server:
  port: 10000

logging:
  level:
    org.jiang.combo.accretion.salute.mapper: debug

spring:
  datasource:
    url: jdbc:mysql://39.104.48.239:3306/accretion_salute_flag
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root1234@
