server:
  port: 9200
  servlet:
    context-path: /admin

# 日志 配置对应包的debug级别
logging:
  level:
    org.jiang.combo.admin.mapper: debug

spring:
  application:
    name: platform
  messages:
    basename: message
    encoding: utf-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://39.104.48.239:3306/combo_project
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root1234@
  redis:
    database: 0
    host: 39.104.48.239
    port: 6379
    password: Redis@123456
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

knife4j:
  enable: true

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_empty
      table-underline: true
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: abcd
  expiration: 1800
  token-head: Bearer
  header-name: Authorization

